package httpx

// Problem represents an RFC 9457 error response.
type Problem struct {
	Type     string `json:"type"`               // A URI reference that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML). When this member is not present, its value is assumed to be "about:blank".
	Title    string `json:"title"`              // A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231], Section 3.4).
	Status   int    `json:"status"`             // The HTTP status code generated by the origin server for this occurrence of the problem.
	Detail   string `json:"detail,omitempty"`   // A human-readable explanation specific to this occurrence of the problem.
	Instance string `json:"instance,omitempty"` // A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
}

func NewProblem(status int, title, detail string) *Problem {
	return &Problem{
		Type:   "about:blank",
		Title:  title,
		Status: status,
		Detail: detail,
	}
}

func (p Problem) Error() string                   { return p.Title }
func (p *Problem) WithType(t string) *Problem     { p.Type = t; return p }
func (p *Problem) WithTitle(t string) *Problem    { p.Title = t; return p }
func (p *Problem) WithStatus(s int) *Problem      { p.Status = s; return p }
func (p *Problem) WithDetail(d string) *Problem   { p.Detail = d; return p }
func (p *Problem) WithInstance(i string) *Problem { p.Instance = i; return p }
